module.exports.EMAIL = {
    ADMIN_EMAIL_SUBJECT: {
        OTPVERIFYNOTIFY: 'OTP for registeration',
        REGISTEREDNOTIFY: 'Congratulations! {sellerName}, Welcome to the Unipick Family',
        NEWPASSWORDNOTIFY: 'Reset your Unipick Password',
        GSTVERIFIEDNOTIFY: 'Welcome to the Unipick Family!',
        SHOPNOTCOMPLETEDNOTIFY: 'Reminder to Setup your Shop',
        PRODUCTNOTCOMPLETEDNOTIFY: 'Reminder to Upload your Products',
        BANKNOTCOMPLETEDNOTIFY: 'Reminder to Complete your Bank details',
        SHOPCOMPLETEDNOTIFY: 'Congratulations! Your profile is active',
        USERAPPROVEDNOTIFY: 'Get ready to start selling on Unipick',
        USERREJECTEDNOTIFY: 'Sorry! We need more information to activate your profile',
        PRODUCTADDEDNOTIFY: 'Congratulations! Your product has been successfully added',
        BULKPRODUCTADDEDNOTIFY: 'Congratulations! Your product has been successfully added',
        PRODUCTAPPROVEDNOTIFY: 'Congratulations! Your product has been approved',
        PRODUCTREJECTEDNOTIFY: 'Sorry! We need more information about your product to activate them',
        CATALOGACTIVENOTIFY: 'Unipick is now accepting orders from Customers',
        LOWINVENTORYNOTIFY: 'Low Stock Alert!',
        PRICEUPDATEDNOTIFY: 'Your product price has been successfully updated',
        QUANTITYUPDATEDNOTIFY: 'Your product inventory has been successfully updated',
        PRODUCTINACTIVENOTIFY: 'Alert! You have marked one or more of your products as `inactive`',
        PRODUCTACTIVENOTIFY: 'Success! You have marked one or more of your products as `active`',
        PRODUCTINACTIVEBYADMINNOTIFY: 'Alert! Your products have been marked as `inactive` by Unipick',
        PRODUCTACTIVEBYADMINNOTIFY: 'Success! Your products have been marked as `active` by Unipick',
        ORDERACCEPTEDNOTIFY: '{sellerName} You have received an order',
        ORDERREADYTOSHIPNOTIFY: 'Order ready to shipped successfully',
        ORDERCANCELLEDNOTIFY: 'Sigh! You got a cancelled order',
        ORDERDELIVEREDNOTIFY: 'Yayyy! Your product has reached its destination',
        ORDERRETURNNOTIFY: 'Oops! You have a return order request on your product',
        ORDERSHIPPEDNOTIFY: 'Your order shipped successfully',
    },
    ADMIN_EMAIL_TEMPLATE: {
        OTPVERIFYNOTIFY: 'OTPVerifyNotify',        
        REGISTEREDNOTIFY: 'RegisteredNotify',
        NEWPASSWORDNOTIFY: 'NewPasswordNotify',
        GSTVERIFIEDNOTIFY: 'GSTVerifiedNotify',
        SHOPNOTCOMPLETEDNOTIFY: 'ShopNotCompletedNotify',
        PRODUCTNOTCOMPLETEDNOTIFY: 'ProductNotCompletedNotify',
        BANKNOTCOMPLETEDNOTIFY: 'BankNotCompletedNotify',
        SHOPCOMPLETEDNOTIFY: 'ShopCompletedNotify',
        USERAPPROVEDNOTIFY: 'UserApprovedNotify',
        USERREJECTEDNOTIFY: 'UserRejectedNotify',
        PRODUCTADDEDNOTIFY: 'ProductAddedNotify',
        BULKPRODUCTADDEDNOTIFY: 'BulkProductAddedNotify',
        PRODUCTAPPROVEDNOTIFY: 'ProductApprovedNotify',
        PRODUCTREJECTEDNOTIFY: 'ProductRejectedNotify',
        CATALOGACTIVENOTIFY: 'CatalogActiveNotify',
        LOWINVENTORYNOTIFY: 'LowInventoryNotify',
        PRICEUPDATEDNOTIFY: 'PriceUpdatedNotify',
        QUANTITYUPDATEDNOTIFY: 'QuantityUpdatedNotify',
        PRODUCTINACTIVEBYADMINNOTIFY: 'ProductInActiveByAdminNotify',
        PRODUCTACTIVEBYADMINNOTIFY: 'ProductActiveByAdminNotify',
        PRODUCTINACTIVENOTIFY: 'ProductInActiveNotify',
        PRODUCTACTIVENOTIFY: 'ProductActiveNotify',
        ORDERACCEPTEDNOTIFY: 'OrderAcceptedNotify',
        ORDERREADYTOSHIPNOTIFY: 'OrderReadyToShipNotify',
        ORDERCANCELLEDNOTIFY: 'OrderCancelledNotify',
        ORDERDELIVEREDNOTIFY: 'OrderDeliveredNotify',
        ORDERRETURNNOTIFY: 'OrderReturnNotify',
        ORDERSHIPPEDNOTIFY: 'OrderShippedNotify'
    },
}
